default_stages: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
        name: End of file fixer
        description: "Ensure files end with a newline"

      - id: check-json
        name: Check JSON
        description: "Check that JSON files are valid"

      - id: check-toml
        name: Check TOML
        description: "Check that TOML files are valid"

      - id: check-xml
        name: Check XML
        description: "Check that XML files are valid"

      - id: check-yaml
        name: Check YAML
        description: "Check that YAML files are valid"

      - id: detect-private-key
        name: Detect private key
        description: "Detect private keys in files"

      - id: trailing-whitespace
        name: Trailing whitespace
        description: "Remove trailing whitespace from files"

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.8
    hooks:
      - id: ruff
        name: Ruff check
        description: "Run 'ruff check' for extremely fast Python linting"
        args: [--fix]

      - id: ruff-format
        name: Ruff format
        description: "Run 'ruff format' for extremely fast Python formatting"

  - repo: local
    hooks:
      - id: ty
        name: ty check
        entry: uv run ty check
        language: python
        types: [python]

  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint
        name: Lint Dockerfiles
        description: Runs hadolint to lint Dockerfiles
        language: system
        types: ["dockerfile"]
        entry: hadolint

ci:
  autoupdate_schedule: weekly
