name: Approver

on:
  pull_request:
    types:
      - opened

jobs:
  approve:
    runs-on: ubuntu-latest

    if: endsWith(github.actor, '[bot]')

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Approve
        run: gh pr review ${{ github.event.number }} --approve
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
