name: Docs

on:
  pull_request:
    paths:
      - ".github/actions/setup-git-config/action.yml"
      - ".github/actions/setup-python-with-uv/action.yml"
      - ".github/workflows/gh-deploy.yml"
      - "docs/**.md"
      - ".python-version"
      - "mkdocs.yml"
      - "pyproject.toml"
      - "uv.lock"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: Pages

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Configure Git Credentials
        uses: ./.github/actions/setup-git-config
        with:
          name: github-actions[bot]
          email: 41898282+github-actions[bot]@users.noreply.github.com

      - name: Setup Python with uv
        uses: ./.github/actions/setup-python-with-uv

      - name: Generate cache id
        id: cache
        run: echo "id=$(find docs -type f -print0 | sort -z | xargs -0 sha256sum mkdocs.yml pyproject.toml uv.lock | sha256sum | awk '{print $1}')" >> "$GITHUB_OUTPUT"

      - name: Save cache
        uses: actions/cache@v5
        with:
          key: mkdocs-material-${{ steps.cache.outputs.id }}
          path: .cache
          restore-keys: mkdocs-material-

      - run: uv run mkdocs gh-deploy --force
