name: Docs

on:
  pull_request:
    paths:
      - ".github/actions/setup-git-config/action.yml"
      - ".github/actions/setup-python-with-uv/action.yml"
      - ".github/workflows/gh-deploy.yml"
      - "docs/**.md"
      - ".python-version"
      - "mkdocs.yml"
      - "pyproject.toml"
      - "uv.lock"

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Configure Git Credentials
        uses: ./.github/actions/setup-git-config
        with:
          name: github-actions[bot]
          email: 41898282+github-actions[bot]@users.noreply.github.com

      - name: Setup Python with uv
        uses: ./.github/actions/setup-python-with-uv

      - name: Generate cache id
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - name: Save cache
        uses: actions/cache@v5
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: mkdocs-material-

      - run: uv run mkdocs gh-deploy --force
