name: Lint

on:
  pull_request:
    paths:
      - ".github/actions/setup-python-with-uv/action.yml"
      - ".github/workflows/lint.yml"
      - "**.py"
      - "**.sql"
      - ".python-version"
      - ".sqlfluff"
      - "pyproject.toml"
      - "ruff.toml"
      - "ty.toml"
      - "uv.lock"

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Python with uv
        uses: ./.github/actions/setup-python-with-uv

      - name: Lint by Ruff
        run: uv run nox -s lint -- --ruff

  sqlfluff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Python with uv
        uses: ./.github/actions/setup-python-with-uv

      - name: Lint by SQLFluff
        run: uv run nox -s lint -- --sqlfluff

  ty:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Python with uv
        uses: ./.github/actions/setup-python-with-uv

      - name: Lint by ty
        run: uv run nox -s lint -- --ty
