name: Release

on:
  pull_request:
    branches:
      - develop
      - main
    types:
      - closed

permissions:
  contents: write
  pull-requests: read

jobs:
  develop:
    if: github.event.pull_request.merged == true && github.base_ref == 'develop'

    runs-on: ubuntu-latest

    environment: Develop

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Update Draft Release
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
          disable-autolabeler: true
          publish: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  production:
    if: github.event.pull_request.merged == true && github.base_ref == 'main'

    runs-on: ubuntu-latest

    environment: Production

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Publish Release
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
          disable-autolabeler: true
          name: ${{ env.VERSION }}
          publish: true
          tag: ${{ env.VERSION }}
          version: ${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.event.pull_request.title }}
