name: Test

on:
  push:
    branches: [main]
    paths:
      - ".github/actions/setup-python-with-uv/action.yml"
      - ".github/workflows/test.yml"
      - "**.py"
      - ".coveragerc"
      - ".env**"
      - ".python-version"
      - "tests"
      - "pyproject.toml"
      - "pytest.ini"
      - "uv.lock"

  pull_request:
    paths:
      - ".github/actions/setup-python-with-uv/action.yml"
      - ".github/workflows/test.yml"
      - "**.py"
      - ".coveragerc"
      - ".env**"
      - ".python-version"
      - "tests"
      - "pyproject.toml"
      - "pytest.ini"
      - "uv.lock"

jobs:
  coverage:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Python with uv
        uses: ./.github/actions/setup-python-with-uv

      - name: Run pytest
        run: |
          uv run nox -s test -- --cov_report xml --junitxml junit.xml

      - name: Upload test results to Codecov
        uses: codecov/test-results-action@v1
        with:
          fail_ci_if_error: true
          files: ./junit.xml,!./cache
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          flags: unittests
          files: ./coverage.xml,!./cache
          token: ${{ secrets.CODECOV_TOKEN }}
